name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-west1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Authorize Docker
        run: gcloud auth configure-docker us-west1-docker.pkg.dev

      # Build and Deploy Backend
      - name: Build and Push Backend
        run: |
          docker build -t us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/amenguide-backend:${{ github.sha }} -t us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/amenguide-backend:latest ./backend
          docker push us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/amenguide-backend --all-tags

      - name: Deploy Backend to Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'amenguide-backend'
          image: 'us-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-deploy/amenguide-backend:${{ github.sha }}'
          region: ${{ env.REGION }}
          env_vars: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            SCRAPER_API_KEY=${{ secrets.SCRAPER_API_KEY }}

      # Build and Deploy Frontend
      - name: Build and Push Frontend
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} \
            --build-arg NEXT_PUBLIC_KAKAO_MAP_API_KEY=${{ secrets.NEXT_PUBLIC_KAKAO_MAP_API_KEY }} \
            -t us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/amenguide-git:${{ github.sha }} \
            -t us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/amenguide-git:latest ./frontend
          docker push us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/amenguide-git --all-tags

      - name: Deploy Frontend to Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'amenguide-git'
          image: 'us-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-deploy/amenguide-git:${{ github.sha }}'
          region: ${{ env.REGION }}


